version: 2
jobs:
  build:
    working_directory: ~/recall/functions
    docker:
      - image: cimg/node:current
    steps:
      - checkout:
        path: ~/recall
      - run:
          name: Install Dependencies
          command: npm install
