version: 2
jobs:
  build:
    working_directory: ~/recall/functions
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
