version: 2
jobs:
  build:
    working_directory: ~/recall/functions
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd functions & npm install
